<?php

/**
 * The configuration file for the database connection for Phinx
 *
 * NOTE: DO NOT EDIT THIS FILE.
 * IF YOU NEED TO CHANGE THE CONFIGURATION, EDIT THE .ENV FILE
 */

// Load database configuration
$dbConfig = require_once __DIR__ . '/database.php';
$default = $dbConfig['default'];
$connections = $dbConfig['connections'];

// Absolute path to the root directory of the project
$rootPath = dirname(__DIR__);

return [
  'paths' => [
    'migrations' => $rootPath . '/database/migrations',
    'seeds' => $rootPath . '/database/seeds',
  ],
  'environments' => [
    'default_migration_table' => 'phinxlog',
    'default_environment' => getenv('APP_ENV') ?? 'development',
    'production' => [
      'adapter' => $connections['mysql']['adapter'],
      'host' => $connections['mysql']['host'],
      'name' => $connections['mysql']['database'],
      'user' => $connections['mysql']['username'],
      'pass' => $connections['mysql']['password'],
      'port' => $connections['mysql']['port'],
      'charset' => $connections['mysql']['charset'],
    ],
    'development' => [
      'adapter' => $connections['mysql']['adapter'],
      'host' => $connections['mysql']['host'],
      'name' => $connections['mysql']['database'],
      'user' => $connections['mysql']['username'],
      'pass' => $connections['mysql']['password'],
      'port' => $connections['mysql']['port'],
      'charset' => $connections['mysql']['charset'],
    ],
    'testing' => [
      'adapter' => $connections['mysql']['adapter'],
      'host' => $connections['mysql']['host'],
      'name' => $connections['mysql']['database'] . '_test',
      'user' => $connections['mysql']['username'],
      'pass' => $connections['mysql']['password'],
      'port' => $connections['mysql']['port'],
      'charset' => $connections['mysql']['charset'],
    ],
  ],
  'version_order' => 'creation',
];
