name: PHP CS Fixer

on:
  push:
    branches: [main, master, dev]
  pull_request:
    branches: [main, master]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          tools: php-cs-fixer

      - name: Install cs2pr
        run: |
          curl -o cs2pr https://github.com/staabm/annotate-pull-request-from-checkstyle/releases/latest/download/cs2pr
          chmod +x cs2pr
          sudo mv cs2pr /usr/local/bin/

      - name: Check code style with diff
        run: php-cs-fixer fix --dry-run --diff --using-cache=no --verbose .

      - name: Run PHP CS Fixer Checkstyle for PR annotations
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          PHP_CS_FIXER_FUTURE_MODE=1 php-cs-fixer fix --config=.php-cs-fixer.dist.php --dry-run --format=checkstyle | /usr/local/bin/cs2pr
